### ISSUE TITLE
Crashing cacheService and getting wrong information by using the RequestService

### ISSUE THREAD

**Issue by marcom4rtinez** [jalapeno-api-gateway/jagw#3]
While testing my Application with the request service i found the following issues:

1. The requestService works with node removal, altough it is slow but sometimes a node removal can cause the container to crash with the following error:
![MicrosoftTeams-image](https://github.com/jalapeno-api-gateway/jagw/assets/26233496/af1a3662-65e4-4ff0-8f48-641bb3fd1798)

This can be reproduced by requesting a Topology from the LsNode requestService, after that removing a device in the network and requesting again from the LsNode requestService. I suspect that the issue is within the cacheService code.

2. The requestService returns wrong information upon deleting of a link. You can delete a link in the network, jalapeno writes it into the arangoDB. However the requestService still returns the link. I suspect the issue to be in the cacheService. This can be reproduced by requesting the LsNodeEdge after that delete a link and requesting it once again. The response is the same both times, no matter the wait time.

**Comment by marcom4rtinez** [comment]
Might be related to https://github.com/jalapeno-api-gateway/jagw-helm/issues/47 and https://github.com/jalapeno-api-gateway/jagw/issues/4

**Comment by jklaiber** [comment]
Closed with #5
